racks:
  - rack_address: 0x22
    firing_time: 2
    descriptions:
      - Mortar Tube 1
      - Mortar Tube 2
      - Mortar Tube 3
      - Mortar Tube 4
      - Mortar Tube 5
      - Mortar Tube 6
      - Misc 1
      - Misc 2
      - Mortar Tube 7
      - Mortar Tube 8
      - Mortar Tube 9
      - Mortar Tube 10
      - Mortar Tube 11
      - Mortar Tube 12
      - Misc 3
      - Misc 4
